upstream lush_guesser_development {
    server unix:/run/lush-guesser/dev/frontend.sock;
    keepalive 16;
}

upstream lush_guesser_production {
    server unix:/run/lush-guesser/prod/frontend.sock;
    keepalive 16;
}

server {
    listen 80;
    listen [::]:80;
    server_name lush-dev.lookmaimanengineer.cc lush.lookmaimanengineer.cc;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name lush-dev.lookmaimanengineer.cc;

    ssl_certificate /etc/nginx/ssl/lush-dev.lookmaimanengineer.cc/fullchain.crt;
    ssl_certificate_key /etc/nginx/ssl/lush-dev.lookmaimanengineer.cc/private.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://lush_guesser_development;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name lush.lookmaimanengineer.cc;

    ssl_certificate /etc/nginx/ssl/lush.lookmaimanengineer.cc/fullchain.crt;
    ssl_certificate_key /etc/nginx/ssl/lush.lookmaimanengineer.cc/private.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://lush_guesser_production;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
